# Generated by Django 4.2.6 on 2024-02-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_refference', models.CharField(max_length=100)),
                ('period', models.FloatField()),
                ('data_value', models.CharField(max_length=100)),
                ('suppressed', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('magnitude', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('series_titel_1', models.CharField(max_length=100)),
                ('series_titel_2', models.CharField(max_length=100)),
                ('series_titel_3', models.CharField(max_length=100)),
                ('series_titel_4', models.CharField(max_length=100)),
                ('series_titel_5', models.CharField(max_length=100)),
            ],
        ),
    ]
